immortal-time: 30
lobby-time: 30
player-min: 16
players-by-team: 5
nb-teams: 4
pvp-time: 600
wall-time: 1200
always-day-lobby: true
always-day-game: true
map-radius: 500
allow-nether: false
map-nether-radius: 750
allow-spectator: true
enable-bungeecord: false
bungeecord-lobby: lobby
player-death-lightning: true
enderpearls-no-damage: true
enable-tracker: true
config-mode: true